collection/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from collection import settings

from collection.views import main, section_catalog, section_collection, \
    information_coin, add_to_collection, my_collection, catalog, remove_from_collection, coin_collection

urlpatterns = [
    url(r'^$', main),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('user_account.urls', namespace='user_account', app_name='user_account')),
    url(r'^', include('feedback.urls', namespace='feedback', app_name='feedback')),
    url(r'^collection/$', my_collection, name='collection'),
    url(r'^collection/(?P<id_section>[0-9]+)/$', section_collection, name='section_collection'),
    url(r'^collection/([0-9]+)/([0-9]+)/(?P<id_collection>[0-9]+)$', coin_collection, name='coin_collection'),
    url(r'^collection/([0-9]+)/(?P<id_coin>[0-9]+)/remove/$', remove_from_collection, name='remove_from_collection'),
    url(r'^catalog/$', catalog, name='catalog'),
    url(r'^catalog/(?P<id_section>[0-9]+)/$', section_catalog, name='section_catalog'),
    url(r'^catalog/([0-9]+)/(?P<id_coin>[0-9]+)/$', information_coin, name='information_coin'),
    url(r'^catalog/([0-9]+)/(?P<id_coin>[0-9]+)/add/$', add_to_collection, name='add_to_collection'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

feedback/urls.py
from django.conf.urls import url
from .views import Messsage

urlpatterns = [
    url(r'^feedback/$', Messsage.as_view(), name='feedback_message'),
]

user_account/urls.py
from django.conf.urls import include, url
from django.contrib.auth.views import logout
from user_account.views import authentication, user_agreement, registration, profile, ChangingEmailForm, \
    ChangingPasswordForm

urlpatterns = [
    url(r'^account/login/$', authentication, name='login'),
    url(r'^account/registration/$', registration, name='registration'),
    url(r'^account/logout/$', logout, {'template_name': 'catalog.html'}, name='logout'),
    url(r'^account/profile/$', profile, name='profile'),
    url(r'^account/profile/contacts/$', ChangingEmailForm.as_view(), name='contacts'),
    url(r'^account/profile/security/$', ChangingPasswordForm.as_view(), name='security'),
    url(r'^account/user_agreement/$', user_agreement, name='user_agreement'),
    url(r'^account/', include('registration.backends.hmac.urls')),
]

user_account/models.py
from django.db import models

# Create your models here.

user_account/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login
from user_account.form import AuthenticationForm, RegistrationForm, ProfileChangingEmailForm, \
    ProfileChangingPasswordForm
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.views.generic.edit import FormView
from django import forms


def authentication(request):
    if request.method == 'POST':
        auth_form = AuthenticationForm(request.POST, auto_id='%s')

        if auth_form.is_valid():
            user_auth = authenticate(username=User.objects.get(email=auth_form.cleaned_data['your_login']),
                                     password=auth_form.cleaned_data['your_password'])

            if user_auth is not None and user_auth.is_active:
                login(request, user_auth)
                return HttpResponseRedirect('/')
            else:
                auth_form.add_error(None, forms.ValidationError(
                    u"Пользователя с такой электронной почтой или паролем не найден"))
    else:
        auth_form = AuthenticationForm(auto_id='%s')

    return render(request, 'login.html', {'auth_form': auth_form, 'reg_form': RegistrationForm(auto_id='%s')})


def registration(request):
    if request.method == 'POST':
        reg_form = RegistrationForm(request.POST, auto_id='%s')
        email_username = reg_form.cleaned_data['email_signup']

        if reg_form.is_valid() and checking_email_user(email_username):
            if create_user(email_username, reg_form.cleaned_data['password_signup']):
                user = authenticate(username=email_username,
                                    password=reg_form.cleaned_data['password_signup'])
                if user is not None and user.is_active:
                    login(request, user)
                    send_notice(email_username)
                    return HttpResponseRedirect('/')
    else:
        reg_form = RegistrationForm(auto_id='%s')

    return render(request, 'login.html', {'auth_form': AuthenticationForm(auto_id='%s'), 'reg_form': reg_form})


def user_agreement(request):
    return render(request, 'user_agreement.html')


def profile(request):
    user = request.user

    if request.method == 'POST':
        changing_email_form = ProfileChangingEmailForm(request.POST, initial={'email': user.email})
        if changing_email_form.has_changed():
            if changing_email_form.is_bound and changing_email_form.is_valid():
                user.email = changing_email_form.cleaned_data['email']
                user.save()
                changing_email_form.saved = True

        changing_password_form = ProfileChangingPasswordForm(request.POST,
                                                             initial={'password_old': user.password,
                                                                      'password_new': ''})
        if changing_password_form.has_changed():
            if changing_password_form.is_bound and changing_password_form.is_valid():
                password_new = changing_password_form.cleaned_data['password_new']
                password_old = changing_password_form.cleaned_data['password_old']
                if password_new != password_old and user.check_password(password_old):
                    user.set_password(password_new)
                    user.save()
                    changing_password_form.saved = True

    else:
        changing_email_form = ProfileChangingEmailForm({'email': user.email})
        changing_password_form = ProfileChangingPasswordForm()

    return render(request, 'profile.html', {'changing_password_form': changing_password_form,
                                            'changing_email_form': changing_email_form})


class ChangingEmailForm(FormView):
    form_class = ProfileChangingEmailForm
    template_name = 'profile_email.html'

    def get_initial(self):
        initial = super(ChangingEmailForm, self).get_initial()
        initial['email'] = self.request.user.email
        return initial

    def get_context_data(self, **kwargs):
        context = super(ChangingEmailForm, self).get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        user = self.request.user
        user.email = form.cleaned_data['email']
        user.save()
        return super(ChangingEmailForm, self).form_valid(form)


class ChangingPasswordForm(FormView):
    form_class = ProfileChangingPasswordForm
    template_name = 'profile_password.html'

    def get_initial(self):
        initial = super(ChangingPasswordForm, self).get_initial()
        initial['password_new'] = self.request.user.email
        print(initial)
        return initial

    def get_context_data(self, **kwargs):
        context = super(ChangingPasswordForm, self).get_context_data(**kwargs)
        context['changing_password_form'] = self.form_class
        return context

    def form_valid(self, form):
        user = self.request.user
        password_new = form.cleaned_data['password_new']
        password_old = form.cleaned_data['password_old']
        if password_new != password_old and user.check_password(password_old):
            user.set_password(password_new)
            user.save()
        return super(ChangingPasswordForm, self).form_valid(form)


def checking_email_user(email):
    return User.objects.filter(email=email).count() == 0


def create_user(email, password):
    user = User.objects.create_user(username=email, email=email, password=password)
    return user.save()


def send_notice(recipient_email):
    file = open('./static/notice.html', 'r')

    subject = u'Регистрация на сайте mycollectioncoin.ru'
    message = file.read()
    from_email = 'qwerty@qwerty.ru'
    recipient_list = [recipient_email]

    send_mail(subject, message, from_email, recipient_list)

user_account/templates/changing_email_form.html
{% extends "profile.html" %}

{% block title %}Изменить адрес электронной почты{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'user_account:profile' %}">Профиль</a> |</li>
    <li> Изменить электронную почту</li>
{% endblock %}
{% block subcontent %}
    <div class="center_block">
        <div id="profile">
            <section>
                <form action="." method="post">
                    {% csrf_token %}
                    <h3>Изменить электронную почту</h3>
                    <p>{% if form.saved %}Сохранено{% endif %}</p>
                    <p>
                        <label for="{{ form.email.name }}">{{ form.email.label }}</label>
                        {{ form.email }}
                    </p>
                    <p class="login button">
                        <input type="submit" value="Сохранить"/>
                    </p>
                </form>
            </section>
        </div>
    </div>
{% endblock %}

user_account/templates/changing_password_form.html
{% extends "profile.html" %}

{% block title %}Изменить пароль{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'user_account:profile' %}">Профиль</a> |</li>
    <li> Изменить пароль</li>
{% endblock %}
{% block subcontent %}
    <div class="center_block">
        <div id="profile">
           <section>
                <form action="." method="post">{% csrf_token %}
                    <h3>Изменить пароль</h3>
                    <p>{% if form.saved %}Сохранено{% endif %}</p>
                    <p>
                        <label for="{{ form.password_old.name }}">{{ form.password_old.label }}</label>
                        {{ form.password_old }}
                    </p>
                    <p>
                        <label for="{{ form.password_new.name }}">{{ form.password_new.label }}</label>
                        {{ form.password_new }}
                    </p>
                    {#                <p>#}
                    {#                    <label for="{{ form.password_new_repeat.name }}">{{ form.password_new_repeat.label }}</label>#}
                    {#                    {{ form.password_new_repeat }}#}
                    {#                </p>#}
                    <p class="login button">
                        <input type="submit" value="Сохранить"/>
                    </p>
                </form>
            </section>
        </div>
    </div>
{% endblock %}

user_account/templates/login.html
{% extends "base.html" %}

{% block title %}Вход{% endblock %}
{% block css %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'user_account/css/auth.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'user_account/css/animate-custom.css' %}" />
{% endblock %}
{% block content %}
    <section>
        <a class="hiddenanchor" id="toregister"></a>
        <a class="hiddenanchor" id="tologin"></a>
        <div id="wrapper">
            <div id="login" class="animate form">
                <form  action="." autocomplete="on" method="post">
                    {% csrf_token %}
                    <h1>Войти</h1>
                    {% if auth_form.non_field_errors %}
                    <div class="errors">
                        {{ auth_form.non_field_errors }}
                    </div>
                    {% endif %}
                    <p>
                        <label for="{{ auth_form.your_login.name }}" data-icon="u">{{ auth_form.your_login.label }}</label>
                        {{ auth_form.your_login }}
                    </p>
                    <p>
                        <label for="{{ auth_form.your_password.name }}" data-icon="p">{{ auth_form.your_password.label }}</label>
                        {{ auth_form.your_password }}
                        {{ auth_form.your_password.errors }}
                    </p>
                    <p class="keeplogin">
                        {{ auth_form.keep_me_login }}
                        <label for="{{ auth_form.keep_me_login.name }}">{{ auth_form.keep_me_login.label }}</label>
                    </p>
                    <p class="login button">
                        <input type="submit" value="Войти" />
                    </p>
                    <p class="change_link">
                        Еще не с нами ?
                        <a href="#toregister" class="to_register">Присоединяйтесь</a>
                    </p>
                </form>
            </div>
            <div id="register" class="animate form">
                <form  action="{% url 'user_account:registration' %}" autocomplete="on" method="post">
                    {% csrf_token %}
                    <h1>Регистрация</h1>
                    <p>
                        <label for="{{ reg_form.email_signup.name }}" data-icon="e">{{ reg_form.email_signup.label }}</label>
                        {{ reg_form.email_signup }}
                    </p>
                    <p>
                        <label for="{{ reg_form.password_signup.name }}" data-icon="p">Ваш пароль</label>
                        {{ reg_form.password_signup }}
                    </p>
                    <p id="user_agreement">
                        Нажимая кнопку &laquoЗарегистрироваться&raquo, Вы принимаете условия <a href="{% url 'user_account:user_agreement' %}" target="_blank">
                        Пользовательского соглашения</a>.
                    </p>
                    <p class="signin button">
                        <input type="submit" value="Зарегистрироваться"/>
                    </p>
                    <p class="change_link">
                        Уже зарегистрированы ?
                        <a href="#tologin" class="to_register">Войти</a>
                    </p>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

user_account/templates/password_reset_complete.html
{% extends "base.html" %}

{% block title %}Пароль изменён{% endblock %}

{% block content %}
    <div class="message">
        <p>Пароль от Вашей учетной записи был успешно изменён,<br> заходите и продолжайте работу.</p>
        <a class="button begin" href="{% url 'user_account:login' %}">ВОЙТИ</a>
    </div>
{% endblock %}

user_account/templates/password_reset_confirm.html
{% extends "base.html" %}

{% block title %}Установка нового пароля{% endblock %}

{% block content %}
    <div class="center_block">
        <form action="" method="post">
            {% csrf_token %}
            <h3>Установка нового пароля</h3>
            {% for field in form %}
                <p>
                    {{ field.label_tag }}{{ field }}
                </p>
            {% endfor %}
{#            <span class="errors">{{ form.email.errors|join:' ' }}</span>#}
            <p class="login button">
                <input type="submit" value="Сохранить"/>
            </p>
        </form>
    </div>
{% endblock %}

user_account/templates/password_reset_done.html
{% extends "base.html" %}

{% block title %}Сброс пароля{% endblock %}

{% block content %}
    <div class="message">
        <p>На указанные адрес электронной почты было отправлено сообщение, содержащее ссылку,<br> по которой необходимо перей для сброса пароля от Вашей учетной записи.</p>
        <a class="button begin" href="{% url 'catalog' %}">Ок</a>
    </div>
{% endblock %}

user_account/templates/password_reset_email.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head lang="en">
    <meta charset="utf-8">
</head>
<body>
    <table cellpadding="0" cellspacing="0" border="0" width="100%" style="text-align: center">
        <tr>
            <td style="font-size: large"><b>Уважаемый пользователь</b></td>
        </tr>
        <tr>
            <td>Для сброса пароля от учетной записи, на сайте {{ site_name }}, Вам необходимо перейти по, указанной ниже, ссылке</td>
        </tr>
        <tr>
            <td><a href="{{ protocol }}://{{ domain }}{% url 'user_account:password_reset_confirm' uidb64=uid token=token %}">Сбросить пароль</a></td>
        </tr>
    </table>
</body>

user_account/templates/password_reset_form.html
{% extends "base.html" %}

{% block title %}Сброс пароля{% endblock %}

{% block content %}
    <div class="center_block">
        <form action="" method="post">
            {% csrf_token %}
            <h3>Сброс пароля</h3>
            <p>
                {{ form.email.label_tag }}{{ form.email }}
                <span class="errors">{{ form.email.errors|join:' ' }}</span>
            </p>
            <p class="login button">
                <input type="submit" value="Продолжить"/>
            </p>
        </form>
    </div>
{% endblock %}

user_account/templates/profile.html
{% extends "base.html" %}

{% block title %}Профиль{% endblock %}

{% block breadcrumbs %}
<li>Профиль</li>
{% endblock %}

{% block content %}
<div class="nav_profile">
    <ul>
        <li>
            <a href="{% url 'user_account:contacts' %}">Контакты</a>
        </li>
        <li>
            <a href="{% url 'user_account:security' %}">Безопасность</a>
        </li>
    </ul>
</div>
{% block profile_item %}
<div id="profile">

</div>
{% endblock %}
{% endblock %}

user_account/templates/profile_email.html
{% extends "profile.html" %}

{% block title %}Профиль - Сменить email{% endblock %}

{% block breadcrumbs %}
<li><a href="{% url 'user_account:profile' %}">Профиль</a></li> |
<li>Сменить email</li>
{% endblock %}

{% block profile_item %}
<div id="profile">
    <section>
        <form action="." method="post">{% csrf_token %}
            <h2>Сменить email</h2>
            <p>{% if form.saved %}Сохранено{% endif %}</p>
            <p>
                <label for="{{ form.email.name }}">{{ form.email.label }}</label>
                {{ form.email }}
            </p>
            <p class="login button">
                <input type="submit" value="Сохранить"/>
            </p>
        </form>
    </section>
</div>
{% endblock %}

user_account/templates/profile_password.html
{% extends "profile.html" %}

{% block title %}Профиль - Сменить пароль{% endblock %}

{% block breadcrumbs %}
<li><a href="{% url 'user_account:profile' %}">Профиль</a></li> |
<li>Сменить пароль</li>
{% endblock %}

{% block profile_item %}
<div id="profile">
    <section>
        <form action="." method="post">{% csrf_token %}
            <h2>Сменить пароль</h2>
            <p>{% if form.saved %}Сохранено{% endif %}</p>
            <p>
                <label for="{{ form.password_old.name }}">
                    {{ changing_password_form.password_old.label }}
                </label>
                {{ changing_password_form.password_old }}
            </p>
            <p>
                <label for="{{ form.password_new.name }}">
                    {{ form.password_new.label }}
                </label>
                {{ form.password_new }}
            </p>
            <!--<p>-->
                <!--<label for="{{ form.password_new_repeat.name }}">-->
                    <!--{{ form.password_new_repeat.label }}</label>#}-->
                <!--{{ form.password_new_repeat }}-->
            <!--</p>-->
            <p class="login button">
                <input type="submit" value="Сохранить"/>
            </p>
        </form>
    </section>
</div>
{% endblock %}

user_account/templates/user_agreement.html
{% extends "base.html" %}

{% block title %}Пользовательское соглашение{%  endblock %}