collection/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from collection import settings

from collection.views import main, section_catalog, section_collection, \
    information_coin, add_to_collection, my_collection, catalog, remove_from_collection, coin_collection

urlpatterns = [
    url(r'^$', main),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('user_account.urls', namespace='user_account', app_name='user_account')),
    url(r'^', include('feedback.urls', namespace='feedback', app_name='feedback')),
    url(r'^collection/$', my_collection, name='collection'),
    url(r'^collection/(?P<id_section>[0-9]+)/$', section_collection, name='section_collection'),
    url(r'^collection/([0-9]+)/([0-9]+)/(?P<id_collection>[0-9]+)$', coin_collection, name='coin_collection'),
    url(r'^collection/([0-9]+)/(?P<id_coin>[0-9]+)/remove/$', remove_from_collection, name='remove_from_collection'),
    url(r'^catalog/$', catalog, name='catalog'),
    url(r'^catalog/(?P<id_section>[0-9]+)/$', section_catalog, name='section_catalog'),
    url(r'^catalog/([0-9]+)/(?P<id_coin>[0-9]+)/$', information_coin, name='information_coin'),
    url(r'^catalog/([0-9]+)/(?P<id_coin>[0-9]+)/add/$', add_to_collection, name='add_to_collection'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

feedback/urls.py
from django.conf.urls import url
from .views import Messsage

urlpatterns = [
    url(r'^feedback/$', Messsage.as_view(), name='feedback_message'),
]

user_account/urls.py
from django.conf.urls import include, url
from django.contrib.auth.views import logout
from user_account.views import authentication, user_agreement, registration, profile, ChangingEmailForm, \
    ChangingPasswordForm

urlpatterns = [
    url(r'^account/login/$', authentication, name='login'),
    url(r'^account/registration/$', registration, name='registration'),
    url(r'^account/logout/$', logout, {'template_name': 'catalog.html'}, name='logout'),
    url(r'^account/profile/$', profile, name='profile'),
    url(r'^account/profile/contacts/$', ChangingEmailForm.as_view(), name='contacts'),
    url(r'^account/profile/security/$', ChangingPasswordForm.as_view(), name='security'),
    url(r'^account/user_agreement/$', user_agreement, name='user_agreement'),
    url(r'^account/', include('registration.backends.hmac.urls')),
]

collection/models.py
from django.db import models
from django.contrib.auth.models import User


class Coin(models.Model):
    name = models.CharField(u'Наименование', max_length=50)
    circulation = models.IntegerField(u'Тираж', null=True, blank=True)
    inscription = models.CharField(u'Надпись на монете', max_length=200, null=True, blank=True)
    year = models.SmallIntegerField(u'Год монеты')
    weight = models.DecimalField(u'Масса монеты', max_digits=5, decimal_places=3, null=True, blank=True)
    diameter = models.DecimalField(u'Диаметр монеты', max_digits=4, decimal_places=2, null=True, blank=True)
    thickness = models.DecimalField(u'Толщина монеты', max_digits=3, decimal_places=2, null=True, blank=True)
    metal = models.ManyToManyField('Metal', verbose_name=u'Металл', db_column='id_metal')
    type_edge = models.ForeignKey('TypeEdge', verbose_name=u'Вид гурта', null=True, blank=True, db_column='id_edge')
    section = models.ForeignKey('Section', verbose_name=u'Раздел', db_column='id_section')
    mint = models.ForeignKey('Mint', verbose_name=u'Монетный двор', null=True, blank=True, db_column='id_mint')

    def __str__(self):
        return u'%s %s' % (self.name, self.year)

    class Meta:
        verbose_name = u'Монета'
        verbose_name_plural = u'Монеты'


class Mint(models.Model):
    name = models.CharField(u'Наименование', max_length=100)

    def __str__(self):
        return u'%s' % (self.name,)

    class Meta:
        verbose_name = u'Монетный двор'
        verbose_name_plural = u'Монетные дворы'


class Image(models.Model):
    image = models.FileField(u'Файл изображения', upload_to='images', blank=True, null=True)
    coin = models.ForeignKey('Coin', verbose_name=u'Монета', db_column='id_coin')

    def __str__(self):
        return u'%s' % (self.image,)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        for field in self._meta.fields:
            if field.name == 'image':
                field.upload_to = 'images/origin/coins/%d' % self.coin.year
        super(Image, self).save()

    class Meta:
        ordering = ['image']
        verbose_name = u'Изображение'
        verbose_name_plural = u'Изображения'


class Metal(models.Model):
    name = models.CharField(u'Наименование металла', max_length=50)

    def __str__(self):
        return u'%s' % (self.name,)

    class Meta:
        verbose_name = u'Металл'
        verbose_name_plural = u'Металлы'


class TypeEdge(models.Model):
    name = models.CharField(u'Вид гурта', max_length=50)

    class Meta:
        db_table = 'collection_type_edge'
        verbose_name = u'Гурт'
        verbose_name_plural = u'Гурт'

    def __str__(self):
        return u'%s' % (self.name,)


class Section(models.Model):
    name = models.CharField(u'Наименование раздела', max_length=200)
    parent_section = models.ForeignKey('Section', verbose_name=u'Корневой раздел', null=True, blank=True,
                                       db_column='id_parent_section', on_delete=models.SET_NULL)

    class Meta:
        ordering = ["name"]
        verbose_name = u'Раздел'
        verbose_name_plural = u'Разделы'

    def __str__(self):
        return u'%s' % (self.name,)


class Grade(models.Model):
    name = models.CharField(u'Грэйд', max_length=30)
    explanation = models.CharField(u'Пояснение', null=True, blank=True, max_length=100)

    class Meta:
        abstract = True


class InternationalGrade(Grade):
    class Meta:
        db_table = 'collection_international_grade'
        verbose_name = u'Международная оценка'
        verbose_name_plural = u'Международные оценки'

    def __str__(self):
        return u'%s' % self.name


class SheldonGrade(Grade):
    class Meta:
        db_table = 'sheldon_grade'
        verbose_name = u'Оценка по Шелдону'
        verbose_name_plural = u'Оценки по Шелдону'

    def __str__(self):
        return u'%s' % self.name


class Collection(models.Model):
    coin = models.ForeignKey('Coin', verbose_name=u'Монета', db_column='id_coin')
    international_grade = models.ForeignKey('InternationalGrade', verbose_name=u'Международная оценка', null=True,
                                            blank=True, db_column='id_international_grade')
    sheldon_grade = models.ForeignKey('SheldonGrade', verbose_name=u'Шелдона оценка', null=True, blank=True,
                                      db_column='id_sheldon_grade')
    user = models.ForeignKey(User, verbose_name=u'Пользователь', db_column='id_user')
    note = models.TextField(u'Заметки', null=True, blank=True)

    class Meta:
        verbose_name = u'Коллекция'
        verbose_name_plural = u'Коллекция'

collection/views.py
from django.shortcuts import render, render_to_response, redirect
from django.template import RequestContext
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from collection.models import Section, Coin, Metal, TypeEdge, Collection
from collection.form import CoinForm, AddToCollectionForm, CollectionForm
import re


def main(request):
    if not request.user.is_authenticated():
        return render(request, 'catalog.html')
    else:
        title = breadcrumbs = u'Каталог'
        section_list = Section.objects.all()
        return render(request, 'catalog.html', {'title': title,
                                                'breadcrumbs': breadcrumbs,
                                                'section_list': section_list})


@login_required
def catalog(request):
    title = breadcrumbs = u'Каталог'
    sections = Section.objects.filter(parent_section=None)
    coins = Coin.objects.all()[:48:3]
    return render(request, 'catalog.html',
                  {'title': title, 'breadcrumbs': breadcrumbs, 'sections': sections, 'coins': coins})


def section_catalog(request, id_section):
    coins = Coin.objects.filter(section=id_section)
    section = Section.objects.get(pk=id_section)

    return render_to_response('section_coin.html',
                              {'section': section, 'coins': sort_coin_name(coins)},
                              context_instance=RequestContext(request))


def sort_coin_name(list_coin):
    pattern = re.compile('([0-9]{1,3}|[А-Яа-я]+)?\s?([А-Яа-я\s]+)')
    dict_coins = {}
    list_sort_coins = []

    for coin in list_coin:
        matches = pattern.match(coin.name)
        val = matches.group(1).lower()

        if val is not None:
            if u'рубл' in val:
                wt = 100
            elif u'один' in val:
                wt = 10
            elif u'пол' in val:
                wt = 0.005
            else:
                wt = int(matches.group(1)) * 0.01

        val = matches.group(2)

        if u'рубл' in val:
            wt = 1

        dict_coins[wt] = coin

    keys_dict_coins = list(dict_coins.keys())
    keys_dict_coins.sort()
    for key in keys_dict_coins:
        list_sort_coins.append(dict_coins[key])

    return list_sort_coins


def information_coin(request, id_coin):
    coin = Coin.objects.get(pk=id_coin)

    metal_list = []
    for metal in coin.metal.all():
        metal_list.append(metal.name)

    if coin.type_edge is not None:
        try:
            type_edge = TypeEdge.objects.get(id__exact=coin.type_edge.id)
            type_edge_name = type_edge.name
        except ObjectDoesNotExist:
            type_edge_name = ""
    else:
        type_edge_name = ""

    coin_form = CoinForm(instance=coin, initial={'type_edge': type_edge_name, 'metal': ','.join(metal_list)},
                         label_suffix='')

    return render_to_response('coin.html', {'coin': coin, 'coin_form': coin_form},
                              context_instance=RequestContext(request))


def add_to_collection(request, id_coin):
    coin = Coin.objects.get(pk=id_coin)

    if request.method == 'POST':
        add_to_collection_form = AddToCollectionForm(request.POST, label_suffix='')
        if add_to_collection_form.is_bound and add_to_collection_form.is_valid():
            collection = add_to_collection_form.save(commit=False)
            collection.coin = coin
            collection.user = request.user
            collection.save()
            return redirect('section_collection', id_section=coin.section_id)
    else:
        add_to_collection_form = AddToCollectionForm(label_suffix='')

    return render(request, 'add_to_collection.html', {'coin': coin,
                                                      'add_to_collection_form': add_to_collection_form})


def my_collection(request):
    title = u'Моя Коллекция'
    sections = Section.objects.filter(coin__collection__user=request.user).distinct()

    return render(request, 'collection.html', {'title': title,
                                               'breadcrumbs': [{'url': '', 'title': title}],
                                               'sections': sections})


def section_collection(request, id_section):
    collections = Collection.objects.filter(user=request.user).filter(coin__section=id_section)
    # coins = Coin.objects.filter(collection__user=request.user).filter(section=id_section)
    # if coins.count():
    #     section = Section.objects.get(pk=id_section)
    # if collections.count():
    #     section = Section.objects.get(pk=id_section)
    # else:
    #     section = coins[0].section.name
    if collections.count():
        section = Section.objects.get(pk=id_section)
    else:
        section = collections[0].section.name

    title = Section.objects.get(pk=id_section).name

    return render(request, 'section_coin.html', {'title': title,
                                                       'section': section,
                                                       'collections': collections})


def coin_collection(request, id_collection):
    collection = Collection.objects.get(pk=id_collection)
    coin = collection.coin

    metal_list = []
    for metal in coin.metal.all():
        metal_list.append(metal.name)

    if coin.type_edge is not None:
        try:
            type_edge = TypeEdge.objects.get(id__exact=coin.type_edge.id)
            type_edge_name = type_edge.name
        except ObjectDoesNotExist:
            type_edge_name = ""
    else:
        type_edge_name = ""

    coin_form = CoinForm(instance=coin, initial={'type_edge': type_edge_name, 'metal': ','.join(metal_list)},
                         label_suffix='')
    collection_form = CollectionForm(instance=collection, label_suffix='')

    return render(request, 'coin_collection.html', {'coin': coin,
                                                    'coin_form': coin_form,
                                                    'collection_form': collection_form})


def remove_from_collection(request, id_coin):
    coin = Coin.objects.get(pk=id_coin)

    # if request.method == 'POST':
    #     add_to_collection_form = AddToCollectionForm(request.POST, label_suffix='')
    #     if add_to_collection_form.is_bound and add_to_collection_form.is_valid():
    #         collection = add_to_collection_form.save(commit=False)
    #         collection.coin = coin
    #         collection.save()
    #         return redirect('coins_section', id_section=coin.section_id)
    # else:
    #     add_to_collection_form = AddToCollectionForm(label_suffix='')

    return render(request, 'remove_from_collection.html')

templates/add_to_collection.html
{% extends "base.html" %}

{% block title %}{{ coin.name }} - {{ coin.section }}{% endblock %}

{% load staticfiles %}

{% block css %}
<link type="text/css" rel="stylesheet" href="{% static 'styles/css/smslider.css' %}"/>
{% endblock %}

{% block js %}
<script type="text/javascript" src="{% static 'js/jquery.smslider.min.js' %}"></script>
{% endblock %}

{% block breadcrumbs %}
<li><a href="{% url 'catalog' %}">Каталог</a></li> |
<li><a href="{% url 'section_catalog' coin.section.id %}">{{ coin.section }}</a></li> |
<li>{{ coin.name }}</li>
{% endblock %}

{% block content %}
<div id="coin">
    <div class="sm_slider">
        <ul>
            {% for image in coin.image_set.all %}
            <li><img src="{{ image.image.url }}" alt="Photo"/></li>
            {% endfor %}
        </ul>
    </div>
    <div id="detail">
        <form action="." method="post">{% csrf_token %}
            {% for field in add_to_collection_form %}
            <p>{{ field.label_tag }}</p>{{ field }}
            {% endfor %}
            <button class="save_button" type="submit">Сохранить</button>
        </form>
    </div>
</div>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
        $(document).ready(function(){
            $('.sm_slider').smSlider({pagination : false});
        });
</script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head lang="en">
    <meta charset="utf-8">
    <title>{% block title %}Коллекция{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles/css/main.css' %}" />
    {% block css %}{% endblock %}
    <script type="text/javascript" src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
    {% block js %}{% endblock %}
</head>
<body>
    <header>
        <nav>
            <ul id="header_menu">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'user_account:logout' %}">Выход</a></li>
                    <li><a href="{% url 'user_account:profile' %}">Профиль</a></li>
                    <li><a href="{% url 'collection' %}">Моя коллекция</a></li>
                {% else %}
                    <li><a href="{% url 'user_account:login' %}">Вход</a></li>
                {% endif %}
                <li><a href="{% url 'catalog' %}">Каталог</a></li>
            </ul>
        </nav>
    </header>
    <div id="content">
        <ul class="breadcrumbs">
            {% block breadcrumbs %}{% endblock %}
        </ul>
        {% block content %}{% endblock %}
        <div id="push" class="clearfix"></div>
    </div>
    <footer>
        <div id="social_buttons">
            <img src="{% static 'images/iconmonstr-vk-1-32.png' %}">
            <img src="{% static 'images/iconmonstr-facebook-1-32.png' %}">
            <img src="{% static 'images/iconmonstr-twitter-1-32.png' %}">
        </div>
        <ul id="footer_nav">
            <li><a href="{% url 'feedback:feedback_message' %}">Обратная связь</a></li>
            <li><a href="{% url 'user_account:user_agreement' %}" target="_blank">Пользовательское соглашение</a></li>
            <li>&copy;&nbsp;2016 CoinCollections</li>
        </ul>
    </footer>
    {% block javascript %}{% endblock %}
</body>
</html>

templates/catalog.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block breadcrumbs %}
<li>Каталог</li>
{% endblock %}

{% block content %}
{% include 'nav_left.html' %}
<div class="view_catalog">
    {% include 'view_catalog.html' %}
</div>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
        $(document).ready(function(){
            $('.image_coin').click( function() {
                $(this).toggleClass('flip');
            });
            $("ul.root_section_catalog li ul").hide();
            $("ul.root_section_catalog li a").click(function() {
                $(this).next().slideToggle();
            });
        });
</script>
{% endblock %}

templates/coin.html
{% extends "base.html" %}

{% block title %}{{ coin.name }} - {{ coin.section }}{% endblock %}

{% load staticfiles %}

{% block css %}
<link type="text/css" rel="stylesheet" href="{% static 'styles/css/smslider.css' %}"/>
{% endblock %}

{% block js %}
<script type="text/javascript" src="{% static 'js/jquery.smslider.min.js' %}"></script>
{% endblock %}

{% block breadcrumbs %}
<li><a href="{% url 'catalog' %}">Каталог</a></li> |
<li><a href="{% url 'section_catalog' coin.section.id %}">{{ coin.section }}</a></li> |
<li>{{ coin.name }}</li>
{% endblock %}

{% block content %}
<div id="coin">
    <div class="sm_slider">
        <ul>
            {% for image in coin.image_set.all %}
            <li><img src="{{ image.image.url }}" alt="Photo"/></li>
            {% endfor %}
        </ul>
    </div>
    <div id="detail">
        <form>
            {% for field in coin_form %}
            {% if not field.value|length_is:"0" and field.value != None %}
            <p class="label">{{ field.label }}</p>
            <p>{{ field.value }}</p>
            {% endif %}
            {% endfor %}
        </form>
    </div>
</div>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
        $(document).ready(function(){
            $('.sm_slider').smSlider({pagination : false});
        });
</script>
{% endblock %}

templates/coin_collection.html
{% extends "base.html" %}

{% block title %}{{ coin.name }} - {{ coin.section }}{% endblock %}

{% load staticfiles %}

{% block css %}
<link type="text/css" rel="stylesheet" href="{% static 'styles/css/smslider.css' %}"/>
{% endblock %}

{% block js %}
<script type="text/javascript" src="{% static 'js/jquery.smslider.min.js' %}"></script>
{% endblock %}

{% block breadcrumbs %}
<li><a href="{% url 'collection' %}">Моя коллекция</a> |</li>
<li><a href="{% url 'section_collection' coin.section.id %}">{{ coin.section.name }}</a> |</li>
<li>{{ coin.name }}</li>
{% endblock %}

{% block content %}
<div id="coin">
    <div class="sm_slider">
        <ul>
            {% for image in coin.image_set.all %}
            <li><img src="{{ image.image.url }}" alt="Photo"/></li>
            {% endfor %}
        </ul>
    </div>
    <div id="detail">
        <p>Колекционные характеристики монеты</p>
        <form>
            {% for field in collection_form %}
            {% if not field.value|length_is:"0" and field.value != None %}
            <p>{{ field.label_tag }}</p>{{ field }}
            {% endif %}
            {% endfor %}
        </form>
        <p>Основные характеристики монеты</p>
        <form>
            {% for field in coin_form %}
            {% if not field.value|length_is:"0" and field.value != None %}
            <p class="label">{{ field.label }}</p>
            <p>{{ field.value }}</p>
            {% endif %}
            {% endfor %}
        </form>
    </div>
</div>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
        $(document).ready(function(){
            $('.sm_slider').smSlider({pagination : false});

            $('#detail > p').click(function () {
                $(this).next().toggleClass('js-hidden');
            });
        });
</script>
{% endblock %}

templates/collection.html
{% extends "base.html" %}

{% block title %}
{{ title }}
{% endblock %}

{% block breadcrumbs %}
<li>Моя коллекция</li>
{% endblock %}

{% block content %}
<div class="nav_catalog">
    {% if user.is_authenticated %}
    {% if sections %}
    <ul>
        {% for section in sections %}
        <li>
            <a href="{% url 'section_collection' section.id %}">{{ section.name }}</a>
        </li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endif %}
</div>
<div class="view_catalog">
    {% include 'view_catalog.html' %}
</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}Главная{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        {% if section_list %}
            <ol class="rounded">
            {%  for section in section_list %}
                <li><a href="{% url 'coins_section' section.id %}"><h3>{{ section.name }}</h3></a></li>
            {% endfor %}
            </ol>
        {% endif %}
    {% endif %}
{% endblock %}

templates/nav_left.html
<div class="nav_catalog">
    {% if user.is_authenticated %}
    {% if sections %}
    <ul class="root_section_catalog">
        {% for root_section in sections %}
        <li>
            <a href="#">{{ root_section.name }}</a>
            {% if root_section.section_set.all %}
                <ul>
                {% for sub_section in root_section.section_set.all %}
                    <li>
                        <a href="{% url 'section_catalog' sub_section.id %}">{{ sub_section.name }}</a>
                    </li>
                {% endfor %}
                </ul>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endif %}
</div>

templates/section.html
{% extends "base.html" %}

{% block title %}{{ section.name }}{% endblock %}

{% block breadcrumbs %}
<li><a href="{% url 'catalog' %}">Каталог</a></li> |
<li>{{ section.name }}</li>
{% endblock %}

{% block content %}
{% for coin in coins %}
<div class="coin">
    <div class="header_coin">
        <a href="{% url 'information_coin' section.id coin.id %}">{{ coin.name }}</a>
    </div>
    <div class="image_coin">
        {% if coin.image_set.all %}
        {% for image in coin.image_set.all %}
        <figure class="{% if forloop.counter == 1 %}avers{% else %}reverse{% endif %}">
            <img src="{{ image.image.url }}"/>
        </figure>
        {% endfor %}
        {% else %}
        <figure>
            {% load staticfiles %}
            <img src="{% static 'images/no_coins.png' %}"/>
        </figure>
        {% endif %}
    </div>
    <a href="{% url 'add_to_collection' section.id coin.id %}" class="add_to_collection">Добавить в коллекцию</a>
</div>
{% endfor %}
{% endblock %}

{% block javascript %}
<script type="text/javascript">
        $(document).ready(function(){
            $('.image_coin').click( function() {
                   if ($(this).children("figure").size() == 2)
                        $(this).toggleClass('flip');
            });
         });
</script>
{% endblock %}

templates/section_coin.html
{% extends "catalog.html" %}

{% block title %}{{ section.name }}{% endblock %}

{% block breadcrumbs %}
{% if collections %}
<li><a href="{% url 'collection' %}">Моя коллекция</a> |</li>
{% else %}
<li><a href="{% url 'catalog' %}">Каталог</a></li> |
{% endif %}
<li>{{ section.name }}</li>
{% endblock %}

{% block content %}
{% if collections %}
{% for collection in collections %}
<div class="coin">
    <div class="header_coin">
        <a href="{% url 'coin_collection' section.id collection.coin.id collection.id%}">{{ collection.coin.name }}</a>
    </div>
    <div class="image_coin">
        {% if collection.coin.image_set.all %}
        {% for image in collection.coin.image_set.all %}
        <figure class="{% if forloop.counter == 1 %}avers{% else %}reverse{% endif %}">
            <img src="{{ image.image.url }}"/>
        </figure>
        {% endfor %}
        {% else %}
        <figure>
            {% load staticfiles %}
            <img src="{% static 'images/no_coins.png' %}"/>
        </figure>
        {% endif %}
    </div>
    <a href="{% url 'remove_from_collection' section.id collection.coin.id %}" class="remove_from_collection">Убрать из
        коллекции</a>
</div>
{% endfor %}
{% else %}
{% for coin in coins %}
<div class="coin">
    <div class="header_coin">
         <a href="{% url 'information_coin' section.id coin.id %}">{{ coin.name }}</a>
    </div>
    <div class="image_coin">
        {% if coin.image_set.all %}
        {% for image in coin.image_set.all %}
        <figure class="{% if forloop.counter == 1 %}avers{% else %}reverse{% endif %}">
            <img src="{{ image.image.url }}"/>
        </figure>
        {% endfor %}
        {% else %}
        <figure>
            {% load staticfiles %}
            <img src="{% static 'images/no_coins.png' %}"/>
        </figure>
        {% endif %}
    </div>
    <a href="{% url 'add_to_collection' section.id coin.id %}" class="add_to_collection">Добавить в коллекцию</a>
</div>
{% endfor %}
{% endif %}
{% endblock %}

{% block javascript %}
<script type="text/javascript">
        $(document).ready(function(){
            $('.image_coin').click( function() {
                   if ($(this).children("figure").size() == 2)
                        $(this).toggleClass('flip');
            });
         });
</script>
{% endblock %}

templates/view_catalog.html
{% for coin in coins %}
<div class="coin">
    <div class="header_coin">
        <a href="{% url 'information_coin' coin.section.id coin.id %}">{{ coin.name }}</a>
    </div>
    <div class="image_coin">
        {% for image in coin.image_set.all %}
        <figure class="{% if forloop.counter == 1 %}avers{% else %}reverse{% endif %}">
            <img src="{{ image.image.url }}"/>
        </figure>
        {% endfor %}
    </div>
    <a href="{% url 'add_to_collection' coin.section.id coin.id %}" class="add_to_collection">Добавить в коллекцию</a>
</div>
{% endfor %}